import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  form: {
    alignItems: "center",
    height: 549,
    width: "100%",
    paddingTop: 32,
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  formWrapper: {
    justifyContent: "center",
    alignItems: "center",
    height: 549,
    width: "100%",
  },
  image: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    resizeMode: "cover",
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  title: {
    marginTop: 0,
    marginBottom: 33,
    fontFamily: "Roboto - medium",
    fontStyle: "normal",
    fontSize: 30,
    color: "#212121",
  },
  input: {
    marginBottom: 16,
    padding: 16,
    height: 50,
    width: 343,
    backgroundColor: "#F6F6F6",
    color: "#212121",

    borderWidth: 1,
    borderRadius: 8,
    borderStyle: "solid",
    borderColor: "#E8E8E8",
  },
  button: {
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    width: 343,
    height: 50,
    backgroundColor: "#FF6C00",
    color: "#FFFFFF",
    borderRadius: 100,
  },
  buttonText: {
    color: "#FFFFFF",
    fontFamily: "Roboto - regular",
    fontStyle: "normal",
    fontSize: 16,
  },
  buttonShowPasswordWrapper: {
    position: "relative",
    flexDirection: "row",
  },
  buttonShowPassword: {
    position: "absolute",
    top: 16,
    right: 16,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
  },
  buttonShowPasswordText: {
    color: "#1B4371",
    fontFamily: "Roboto - regular",
    fontStyle: "normal",
    fontSize: 16,
  },
  linkWrapper: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  registrationLink: {
    marginRight: 5,
    color: "#1B4371",
    fontFamily: "Roboto - regular",
    fontStyle: "normal",
    fontSize: 16,
  },
  link: {
    color: "#1B4371",
    fontFamily: "Roboto - regular",
    fontStyle: "normal",
    fontSize: 16,
  },
});
